jwt:
  secret: bWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBpbWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBpbWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBpbWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBp
  token:
    accessTokenTTL: 43200   #12시간
    refreshTokenTTL: 2592000 #30일
    issure: loclahost:8080
logging:
  level:
    root: info
spring:
  config:
    activate:
      on-profile: "jwt"