spring:
  redis:
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: spring123
    url: jdbc:mysql://localhost:3306/bookstorage?serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  config:
    activate:
      on-profile: "dev"
logging:
  level:
    org.hibernate.type.descroptor.sql: trace