spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: spring123
    url: jdbc:mysql://localhost:3306/bookstorage?serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
jwt:
  secret: bWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBpbWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBpbWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBpbWUuZGV2a3NoOTMwLmJvb2tzdG9yYWdlQXBp
  token:
    accessTokenTTL: 43200   #12시간
    refreshTokenTTL: 2592000 #30일
    issure: loclahost:8080
logging:
  level:
    root: info