spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: spring123
    url: jdbc:mysql://localhost:3306/bookstorage?serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
